[package]
name = "muxio-tokio-rpc-client"
edition.workspace = true
version.workspace = true 
repository.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
async-trait = "0.1.88"
bytes = "1.10.1"
futures-util = "0.3.31"
tokio = { version = "1.45.1", features = ["full"] }
tokio-tungstenite = "0.26.2"
muxio = { path = "../../" }
muxio-rpc-service = { path = "../muxio-rpc-service" }
muxio-rpc-service-caller = { path = "../muxio-rpc-service-caller", features=["tokio_support"] }
futures = "0.3.31"

[dev-dependencies]
muxio-tokio-rpc-server = { path = "../muxio-tokio-rpc-server" }
example-muxio-rpc-service-definition = { path = "../../example-muxio-rpc-service-definition" }
