[package]
name = "example-muxio-rpc-service-definition"
edition.workspace = true
version.workspace = true 
repository.workspace = true
license.workspace = true
publish = false # Explcitly false

[dependencies]
bitcode = "0.6.6"
muxio-rpc-service = { workspace = true }
