[package]
name = "muxio-rpc-service-caller"
version = "0.1.0-alpha"
edition = "2024"
license = "Apache-2.0"
publish = false

[dependencies]
async-trait = "0.1.88"
futures = "0.3.31"
muxio = { path = "../../" }
muxio-rpc-service = { path = "../muxio-rpc-service" }

# Optional dependencies
tokio = { version = "1.45.1", features = ["sync"], optional = true }

[features]
default = []
tokio_support = ["dep:tokio"]

[dev-dependencies]
tokio = { version = "1.45.1", features = ["full"] }
example-muxio-rpc-service-definition = { path = "../../example-muxio-rpc-service-definition" }
