[workspace.package]
authors = ["Jeremy Harris <jeremy.harris@zenosmosis.com>"]
version = "0.4.0-alpha"
edition = "2024"
repository = "https://github.com/jzombie/rust-muxio"
license = "Apache-2.0"

[package]
name = "muxio"
description = "Toolkit for layered stream multiplexing and schemaless RPC communication."
edition.workspace = true
version.workspace = true 
repository.workspace = true
license.workspace = true

[workspace]
members = [
    ".",
    "example-muxio-ws-rpc-app",
    "extensions/muxio-tokio-rpc-client",
    "extensions/muxio-wasm-rpc-client",
    "extensions/muxio-tokio-rpc-server",
    "extensions/muxio-rpc-service",
    "extensions/muxio-rpc-service-caller",
    "extensions/muxio-rpc-service-endpoint",
    "example-muxio-rpc-service-definition",
]
resolver = "2"

[dependencies]
chrono = "0.4.41"
once_cell = "1.21.3"
tracing = "0.1.41"

[dev-dependencies]
bitcode = "0.6.6"
rand = "0.9.1"
tokio = { version = "1.45.1", features = ["full"] }
