# This configuration file tells `cargo-release` how to handle versions.
# Put this file in the root of your project: /home/jeremy/Projects/rust-muxio/release.toml

# When you run `cargo release patch`, if the current version is a pre-release,
# this setting tells it to increment the pre-release tag instead of finalizing the version.
pre-release-commit-message = "chore(release): release {{version}}"
pre-release-hook = ["git", "push", "--follow-tags"]

# This is the key setting.
# It tells `cargo-release` to bump the pre-release identifier when you run `cargo release patch`.
# So `0.4.0-alpha.0` will become `0.4.0-alpha.1`.
# If you run `cargo release minor`, `0.4.0-alpha.0` would become `0.5.0-alpha.0`.
# pre-release-replacements = [
#  {file="CHANGELOG.md", search="Unreleased", replace="{{version}}"},
# ]
