# This key explicitly defines the order in which crates are published,
# overriding the default dependency-based ordering.
publish-order = [
    "muxio",
    "example-muxio-rpc-service-definition",
    "muxio-rpc-service",
    "muxio-rpc-service-caller",
    "muxio-rpc-service-endpoint",
    "muxio-tokio-rpc-server",
    "muxio-tokio-rpc-client",
    "muxio-wasm-rpc-client",
]
