[package]
name = "muxio-rpc-service"
version = "0.1.0-alpha"
edition = "2024"
publish = false

[dependencies]
async-trait = "0.1.88"
muxio = { path = "../../" }
xxhash-rust = { version = "0.8.15", features = ["xxh3", "const_xxh3"] }
