[package]
name = "example-muxio-ws-rpc-app"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
tokio = { version = "1.45.1", features = ["full"] }
muxio = { path = "../" }
async-trait = "0.1.88"
muxio-tokio-rpc-server = { path = "../extensions/muxio-tokio-rpc-server" }
muxio-tokio-rpc-client = { path = "../extensions/muxio-tokio-rpc-client" }
muxio-rpc-service = { path = "../extensions/muxio-rpc-service" }
muxio-rpc-service-caller = { path = "../extensions/muxio-rpc-service-caller", features=["tokio_support"] }
example-muxio-service-definition = { path = "../example-muxio-service-definition" }

[[bench]]
name = "roundtrip"
harness = false

[dev-dependencies]
criterion = { version = "0.6.0", features = ["async_tokio"] }
futures = "0.3.31"
