[package]
name = "muxio-wasm-rpc-client"
version = "0.1.0-alpha"
edition = "2024"
publish = false

[dependencies]
futures = "0.3.31"
js-sys = "0.3.77"
muxio = { path = "../../" }
wasm-bindgen = "0.2.100"
web-sys = { version = "0.3.77", features = ["console"] }

