[package]
name = "muxio-wasm-rpc-client"
version = "0.1.0-alpha"
edition = "2024"
publish = false

[dependencies]
async-trait = "0.1.88"
futures = "0.3.31"
js-sys = "0.3.77"
muxio = { path = "../../" }
wasm-bindgen = "0.2.100"
muxio-rpc-service = { path = "../muxio-rpc-service" }
wasm-bindgen-futures = "0.4.50"
