[package]
name = "muxio-rpc-service-endpoint"
version = "0.1.0-alpha"
edition = "2024"
publish = false

[dependencies]
async-trait = "0.1.88"
futures = "0.3.31"
muxio = { path = "../../" }
muxio-rpc-service = { path = "../muxio-rpc-service" }
muxio-rpc-service-caller = { path = "../muxio-rpc-service-caller" }

# Optional dependencies
tokio = { version = "1.45.1", features = ["sync"], optional = true }

[features]
default = []
tokio_support = [
    "dep:tokio", # Enables the optional tokio dependency in THIS crate.
    "muxio-rpc-service-caller/tokio_support" # Enables the feature in the CALLER crate.
]

[dev-dependencies]
# doc-comment = "0.3.3" # TODO: Re-enable
tokio = { version = "1.45.1", features = ["full"] }
